# Generated by Django 4.2 on 2024-07-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_porton', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
    ]
