# Generated by Django 4.2 on 2024-07-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transporte', models.CharField(max_length=20, unique=True)),
                ('cargado', models.BooleanField(default=False)),
                ('ultima_ubicacion', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='movimientos.ubicacion')),
            ],
        ),
    ]
