# Generated by Django 4.2 on 2024-07-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_puesto_primer_tiempo_puesto_segundo_tiempo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador',
            options={'verbose_name_plural': 'Operadores'},
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre_puesto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
