# Generated by Django 4.2 on 2024-07-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0007_alter_operador_options_alter_puesto_nombre_puesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operador',
            old_name='nombre_completo',
            new_name='datos_operador',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='registro',
        ),
        migrations.AlterField(
            model_name='puesto',
            name='operador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puesto', to='movimientos.operador'),
        ),
    ]
