# Generated by Django 4.2 on 2024-07-05 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimientos', '0008_rename_nombre_completo_operador_datos_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operador',
            name='datos_operador',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
