# Generated by Django 4.2 on 2024-07-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0009_puesto_usuario_alter_operador_datos_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='usuario',
        ),
    ]
