# Generated by Django 4.2 on 2024-07-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0016_alter_movimiento_ubicacion_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='ubicacion_final',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_final', to='movimientos.ubicacion'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='ultima_ubicacion',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='movimientos.ubicacion'),
        ),
    ]
